AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 180

Resources:
  CreateTodo:
    Type: AWS::Serverless::Function
    Properties:
      Handler: create-todo/dist/bundle.handler
      Environment:
        Variables:
          TABLE_NAME: todos
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /todos
            Method: POST
            Auth:
              Authorizer: NONE
