AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 180
    Handler: bundle.handler
    Environment:
      Variables:
        REGION: eu-central-1
        REGION_DB: eu-west-3
        TABLE_NAME: todos

Resources:
  createTodo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/create-todo/dist
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /todos
            Method: POST
            Auth:
              Authorizer: NONE
  fanout:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/fanout/dist
