AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
Resources:
  CreateTodoFunction:
    Type: AWS::Serverless::Function
    FunctionName: createTodoFunction
    Properties:
      Handler: dist/bundle.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          TABLE_NAME: !Ref TODO
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /
            Method: POST
            Auth:
              Authorizer: NONE
  TODO:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
